# Generated by Django 3.1.2 on 2020-11-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='logo',
            new_name='neighbourhood_logo',
        ),
    ]
