# Generated by Django 3.1.2 on 2021-04-11 20:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
           
        ),
    ]
