# Generated by Django 3.1.2 on 2021-04-11 20:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
